global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "drift_monitor"
    static_configs:
      - targets: ["host.docker.internal:8000"]  # Windows Docker Desktop
    scrape_interval: 60s
    metrics_path: /metrics